### ISSUE TITLE
Gmail Brute-Force not recognizing password

### ISSUE THREAD

**Issue by DagerCo** [RedKatz/SocialMediaHackingToolkit#102]
I tested this tool with a spare Gmail account and put in the correct password in a word list, however it did not identify the correct password, I really need help please.

**Comment by RedKatz** [comment]
Gmail (unfortunately) has (for the past few years) started using separate passwords created specifically for third-party apps, so when the script performs the bruteforce attack it is not looking for the actual password but the password for the apps that still allows access to the account.

Here how the new login system works (at least as far as python and secure-smtp are concerned)

>https://stackoverflow.com/questions/33286691/gmail-smtp-requires-an-app-password
