### ISSUE TITLE
./linux.sh

### ISSUE THREAD

**Issue by sanjukutty** [RedKatz/SocialMediaHackingToolkit#106]
what command do you run that gives you as output this error?

_Originally posted by @RedKatz in https://github.com/RedKatz/SocialMediaHackingToolkit/issues/14#issuecomment-1407652731_
            
![IMG_20230801_215509](https://user-images.githubusercontent.com/141067952/257580280-00acc52e-dd0f-4e77-ba86-98ca0831abf5.jpg)
![IMG_20230801_215509](https://user-images.githubusercontent.com/141067952/257580369-c6fe2068-860f-49fe-a4a3-6af163117ccf.jpg)
Pls pls check this pls pls pls

**Comment by arukhan111** [comment]
Plz help me

**Comment by arukhan111** [comment]
Post on same issu plz any solution

**Comment by arukhan111** [comment]
> ```
>           what command do you run that gives you as output this error?
> ```
> 
> _Originally posted by @RedKatz in [#14 (comment)](https://github.com/RedKatz/SocialMediaHackingToolkit/issues/14#issuecomment-1407652731)_
> 
> ![IMG_20230801_215509](https://user-images.githubusercontent.com/141067952/257580280-00acc52e-dd0f-4e77-ba86-98ca0831abf5.jpg) ![IMG_20230801_215509](https://user-images.githubusercontent.com/141067952/257580369-c6fe2068-860f-49fe-a4a3-6af163117ccf.jpg) Pls pls check this pls pls pls

Same error plz how to fix this error

**Comment by TheZetsu** [comment]
Run: pip3 install rich 
This will install the rich package and should resolve the ModuleNotFoundError. 
Once the rich module is installed, you can try running your script again to see if the error is resolved. Don’t forget to install the requirements  to not have other errors like this run cd: SocialMediaHackingToolkit then run cd cmd and then pip3 install -r requirements.txt i hope this help
