### ISSUE TITLE
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

### ISSUE THREAD

**Issue by ghost** [RedKatz/SocialMediaHackingToolkit#108]
Im having issues downloading winscribe, gives me an error about logging in when the credentials are correct, 

i bypassed that and successfully used the SMH where i see the choosing options. i added the world list with different passwords but one is the correct one, 

For each time it tries the passwords on instagram, i am getting an 
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

any help?

i am on remote desktop connection in Kali Linux

**Comment by Victorcassiano** [comment]
I have the same problem on windows 11

**Comment by kali-static** [comment]
Same on Kali Linux

**Comment by TOXIC-LEGEND** [comment]
I have the same problem

**Comment by aahdbshara** [comment]
i had the same problem!!! there is no one can solve it??

**Comment by Kokothecreator** [comment]
Same problem, no solution

**Comment by RedKatz** [comment]
the problem is caused by the ip being banned which being banned does not allow to receive all the data from the json file, try cmahing ip or enabling vpn

**Comment by aahdbshara** [comment]
am using vpn and i still had this issue please anyone help me with thattttttttt

**Comment by bunnyisgenius** [comment]
Same, am using vpn but still got:
JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C]

**Comment by awwad-abood** [comment]
I used vpn and also tried it after a while, but unfortunately the problem was not solved. Please help

**Comment by awwad-abood** [comment]
@RedKatz Please help

**Comment by awwad-abood** [comment]
@RedKatz can you give me tool better than it because that tool its not work
