### ISSUE TITLE
Word list 

### ISSUE THREAD

**Issue by sanjukutty** [RedKatz/SocialMediaHackingToolkit#112]
Bro pls tell me pls pls 
1) how to create a word list folder (+)
2)How to insert in word list 
Pls pls pls pls reply me or send the 
Full detailed video for this Attack 
Pls pls pls pls pls pls pls pls pls pls pls pls pls
Pls bro pls give a proper solution pls pls pls

**Comment by Ray-ly-04** [comment]
Download a word list and move it to word list by using mv command :) hope this helps

**Comment by Kokothecreator** [comment]
> 

Please link on a place to download a word list and how to successfully move it

**Comment by Kokothecreator** [comment]
> Bro pls tell me pls pls
> 
> 1. how to create a word list folder (+)
>    2)How to insert in word list
>    Pls pls pls pls reply me or send the
>    Full detailed video for this Attack
>    Pls pls pls pls pls pls pls pls pls pls pls pls pls
>    Pls bro pls give a proper solution pls pls pls

Please if you got a solution tell me how you did it also

**Comment by Ray-ly-04** [comment]
You can find rockyou.txt on Google ;)
