### ISSUE TITLE
insta bruteforce issue

### ISSUE THREAD

**Issue by aahdbshara** [RedKatz/SocialMediaHackingToolkit#113]
HI. when i try to run the bruteforce on instagram i get a problem its said (JSON Query to accounts/login/: Could not find "window._sharedData" in html response. [retrying; skip with ^C])

please. if any one can solve this problem help me. thank you

![Screenshot_2023-08-12_23_42_44](https://github.com/RedKatz/SocialMediaHackingToolkit/assets/77169280/cba6a619-ef5f-447f-9b58-83f199f80590)

**Comment by VictorPeratLHS** [comment]
I have the same problem, I have been 4 hours trying to solve it, but i'm not able. :C

**Comment by bunnyisgenius** [comment]
I have the same problem too, did anyone solve this?

**Comment by RedKatz** [comment]
the problem is caused by the ip being banned which being banned does not allow to receive all the data from the json file, try cmahing ip or enabling vpn
