### ISSUE TITLE
Проблема с wordlist

### ISSUE THREAD

**Issue by esconne** [RedKatz/SocialMediaHackingToolkit#114]
когда выбираешь gmail bruteforce и где нужно указать путь к wordlist(список паролей) 
то выдает ошибку
Error1x01: wordlist not found, please insert your wordlist in 'wordlist' folder

А я указываю прямой путь к нему и через папку wordlist но он не видит этого файла хотя он там есть!

**Comment by esconne** [comment]
@**RadKatz**

**Comment by Ayza2326** [comment]
> когда выбираешь gmail bruteforce и где нужно указать путь к wordlist(список паролей) то выдает ошибку Error1x01: wordlist not found, please insert your wordlist in 'wordlist' folder
> 
> А я указываю прямой путь к нему и через папку wordlist но он не видит этого файла хотя он там есть!

Hello, This is Shohag. I am a professional Ethical Hacker,
Security Specialist as well as Penetration Tester. I can test the following vulnerability and I will provide you with a perfect assessment of your website security
which makes your website safe and sound.

My Experience:
💗. Recovering Hacked WordPress Website
💗. Full Vulnerability Scan and WordPress website malware removal
💗. Vulnerability Assessment
💗. Antispam protection
💗. Analysis of database servers
💗. Restore a hacked website
💗. Ethical Hacking(White Hat Hacker)
💗. Hacked account recovery
💗. Password recovery
💗. Decode encrypted files
💗. Vulnerability Testing
💗....my  WhatsApp number +8801314956025

**Comment by RedKatz** [comment]
wait for the next version, the problem will be fixed
