### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by fawaz13412** [RedKatz/SocialMediaHackingToolkit#116]
i don't know how to fix this 

Traceback (most recent call last):
  File "/home/kali/SocialMediaHackingToolkit/cmd/main.py", line 25, in <module>
    insta_bruteforce(username, wordlist, vpn)
  File "/home/kali/SocialMediaHackingToolkit/cmd/utils.py", line 133, in insta_bruteforce
    wl_lines = [line.strip() for line in wl_file.readlines()]  # Rimuovi i caratteri di nuova riga
                                         ^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 933: invalid continuation byte
                                                                                                        

can anyone help me?

**Comment by Ray-ly-04** [comment]
I got the same error

**Comment by Ayza2326** [comment]
> i don't know how to fix this
> 
> Traceback (most recent call last): File "/home/kali/SocialMediaHackingToolkit/cmd/main.py", line 25, in insta_bruteforce(username, wordlist, vpn) File "/home/kali/SocialMediaHackingToolkit/cmd/utils.py", line 133, in insta_bruteforce wl_lines = [line.strip() for line in wl_file.readlines()] # Rimuovi i caratteri di nuova riga ^^^^^^^^^^^^^^^^^^^ File "", line 322, in decode UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 933: invalid continuation byte
> 
> can anyone help me?

Hello, This is Shohag. I am a professional Ethical Hacker,
Security Specialist as well as Penetration Tester. I can test the following vulnerability and I will provide you with a perfect assessment of your website security
which makes your website safe and sound.

My Experience:
💗. Recovering Hacked WordPress Website
💗. Full Vulnerability Scan and WordPress website malware removal
💗. Vulnerability Assessment
💗. Antispam protection
💗. Analysis of database servers
💗. Restore a hacked website
💗. Ethical Hacking(White Hat Hacker)
💗. Hacked account recovery
💗. Password recovery
💗. Decode encrypted files
💗. Vulnerability Testing
💗....my  WhatsApp number +8801314956025

**Comment by RedKatz** [comment]
the wordlist you are using contains characters that cannot be correctly represented in UTF-8, change wordlist and it should work correctly
