### ISSUE TITLE
Little Help

### ISSUE THREAD

**Issue by Kokothecreator** [RedKatz/SocialMediaHackingToolkit#118]
I made a successful installation but I'm a stuck on how to properly run the tool. I use Termux, please a little help or guidance 
![Screenshot_2023-08-24-11-52-06-883_com termux](https://github.com/RedKatz/SocialMediaHackingToolkit/assets/86709156/f2c4721e-6597-4546-932e-02db672de751)

**Comment by Ayza2326** [comment]
> I made a successful installation but I'm a stuck on how to properly run the tool. I use Termux, please a little help or guidance ![Screenshot_2023-08-24-11-52-06-883_com termux](https://user-images.githubusercontent.com/86709156/262950857-f2c4721e-6597-4546-932e-02db672de751.jpg)
Hello, This is Shohag. I am a professional Ethical Hacker,
Security Specialist as well as Penetration Tester. I can test the following vulnerability and I will provide you with a perfect assessment of your website security
which makes your website safe and sound.

My Experience:
💗. Recovering Hacked WordPress Website
💗. Full Vulnerability Scan and WordPress website malware removal
💗. Vulnerability Assessment
💗. Antispam protection
💗. Analysis of database servers
💗. Restore a hacked website
💗. Ethical Hacking(White Hat Hacker)
💗. Hacked account recovery
💗. Password recovery
💗. Decode encrypted files
💗. Vulnerability Testing
💗....my  WhatsApp number +8801314956025.

**Comment by RedKatz** [comment]
run `python3 linux.sh`
