### ISSUE TITLE
Kali Linux installation fail

### ISSUE THREAD

**Issue by WickedHag** [RedKatz/SocialMediaHackingToolkit#131]
sudo dpkg -i windscribe-cli.deb 
- error processing package winscribe- cli

**Comment by TYehan** [comment]
> sudo dpkg -i windscribe-cli.deb
> 
> * error processing package winscribe- cli

git clone https://github.com/RedKatz/SocialMediaHackingToolkit

cd SocialMediaHackingToolkit

cd dependancies  👈

sudo dpkg -i windscribe-cli.deb

windscribe login  👈

cd ../cmd

pip3 install -r requirements.txt

cd ..

chmod +x linux.sh

./linux.sh



<b> Try this one out </b>

**Comment by WickedHag** [comment]
Hello Tyehan,

This is what I get after this command below.

$ sudo dpkg -i windscribe-cli.deb


(Reading database ... 707133 files and directories currently installed.)
Preparing to unpack windscribe-cli.deb ...
Unpacking windscribe-cli (1.4-51) over (1.4-51) ...
dpkg: dependency problems prevent configuration of windscribe-cli:
 windscribe-cli depends on resolvconf; however:
  Package resolvconf is not installed.

dpkg: error processing package windscribe-cli (--install):
 dependency problems - leaving unconfigured
Processing triggers for kali-menu (2023.4.5) ...
Processing triggers for runit (2.1.2-54) ...
Errors were encountered while processing:
 windscribe-cli

**Comment by Giovix0** [comment]
I solved it like this:
sudo apt update
sudo apt upgrade
sudo apt-get -f install
