### ISSUE TITLE
Crashing after wordlist

### ISSUE THREAD

**Issue by ratkaimartin** [RedKatz/SocialMediaHackingToolkit#132]
Hello a started to run rockyou.txt but always crashing. 
Any help ?
Thank you

**Comment by aahdbshara** [comment]
Well try another wordlist

**Comment by vinn85** [comment]
Why it is in loop saying Could not find "window._s hareddata" in the html response. ???

Please help!

**Comment by ratkaimartin** [comment]
I tried a lots of wordlist bu always crashing, do you have any worldlist whick is working ?

**Comment by arukhan111** [comment]
Worldlist error bro

**Comment by Stange3** [comment]
How to make a wordlist code

**Comment by muthupandi143122** [comment]
![Screenshot_20230913-015503](https://github.com/RedKatz/SocialMediaHackingToolkit/assets/144848790/e6852436-7934-442b-97d2-cb2995b65619)
How to solve this

**Comment by gurjeetsinghvirdee** [comment]
> ![Screenshot_20230913-015503](https://user-images.githubusercontent.com/144848790/267453416-e6852436-7934-442b-97d2-cb2995b65619.png) How to solve this

try spongebob.txt as it is last updated on sep 3
