### ISSUE TITLE
how to use phising tool?

### ISSUE THREAD

**Issue by ausiee** [RedKatz/SocialMediaHackingToolkit#18]
when i try to use phising tool it just does nothing then when i click enter it just exits back to the main terminal, is there a spererate program i need to install (im on linux btw)

**Comment by cachoeiraronaldo** [comment]
how i turn on the smhtoolkit in the terminal

**Comment by RedKatz** [comment]
in the 0.3.1 the phishing option is off, this option will be turned on in the next 0.3.2
