### ISSUE TITLE
is not true the "Wrong password:"

### ISSUE THREAD

**Issue by Wolduur737** [RedKatz/SocialMediaHackingToolkit#19]
I test the tools and I pick up a password from the list to test it if it works. but the password I pickup was "Wrong password:"

**Comment by RedKatz** [comment]
most likely your ip has been banned, it happens if you vnegate multiple passwords, I'm looking for a way to prevent this from happening but for now I sleep "succeeded" only with instagram, for the rest in the next version should be integrated a proxy system

**Comment by amanpatel6778** [comment]
This tool showing fake brute force because I checked it on my Instagram account 
I checked this tool on my Instagram account with many wrong password and one original password but this tool showing me all password is wrong so this tool is not working properly and showing fake brute force attack.
