### ISSUE TITLE
create a wordlist

### ISSUE THREAD

**Issue by Hermahas** [RedKatz/SocialMediaHackingToolkit#22]
Hey friends, i'm a noob but tryna use this tool. I would just like to know how to create a wordlist so i can add words that i think is used for the account i'm tryna brute force. Can someone tell me a quick stp by step command for that. Thank you :}

**Comment by RedKatz** [comment]
create or download wl and add it to folder of the program

**Comment by ABD123758** [comment]
How to add bro plz help
