### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by Notneededtoknow** [RedKatz/SocialMediaHackingToolkit#28]

**Comment by RedKatz** [comment]
can you give more info?

**Comment by Brett3011** [comment]
> can you give more info?

it dont find the txt file

**Comment by anshy66566** [comment]
I have a 7 years old Facebook account, I want to open it.
Sukha Khadkhatri
Add this email to that Facebook ID. ***@***.***
pls

**Comment by RedKatz** [comment]
is in the same directory of smh.py

**Comment by RedKatz** [comment]
fixed in new version, 0.3.2, please report any type of error
