### ISSUE TITLE
Not able to run the program itself

### ISSUE THREAD

**Issue by fuulol** [RedKatz/SocialMediaHackingToolkit#30]
**This may be more of a help request** I am decently new to python and I cannot find an answer on how to run the physical program, basically I am trying to get to the area that is included in the gif.

**Comment by RedKatz** [comment]
can you give more info?

**Comment by teate28** [comment]
> can you give more info?

doesnt work for me either. write me on twt wifeofboelacc

**Comment by rylen1829123** [comment]
how do i start the program i installed it but it doesnt say how to start

**Comment by RedKatz** [comment]
to run the program if you are on windows run "python3 smh.py", however the new version of the program is coming, the whole code has been rewritten

**Comment by RedKatz** [comment]
fixed in new version, 0.3.2, please report any type of error
