### ISSUE TITLE
this doesnt even work

### ISSUE THREAD

**Issue by fffgg291** [RedKatz/SocialMediaHackingToolkit#31]
![image](https://user-images.githubusercontent.com/129136678/228116464-14fbf1ba-403d-4727-9138-3cec487b778c.png)
i type in windows and it just closes. dont bother installing it just doesnt work .

**Comment by RedKatz** [comment]
at least try to ask for help before coming to the conclusion....
anyway can you give me any additional information? or does the installer return no output?

**Comment by Darksowlss** [comment]
How to start this thing when you close the window ?

**Comment by RedKatz** [comment]
python3 smh.py
