### ISSUE TITLE
Crashing?

### ISSUE THREAD

**Issue by SenpaiFakita** [RedKatz/SocialMediaHackingToolkit#32]
hello i have problem, i want to try it but when i get to wordlist (idk what to put there) it just crashes and do nothing

**Comment by gunjankalitanb** [comment]
Type rockyou.txt

**Comment by RedKatz** [comment]
fixed in new version, 0.3.2, please report any type of error

**Comment by SenpaiFakita** [comment]
> rockyou.txt

okay i tried it but it just truned of idk what to do. Is there some tutorial?

**Comment by RedKatz** [comment]
can you send a gif? i tryed on windows vm and work good
