### ISSUE TITLE
it is crashing

### ISSUE THREAD

**Issue by teate28** [RedKatz/SocialMediaHackingToolkit#39]
I tried to install this on windows laptop but it crashes. can someone hack/ ban account for me named 
markobosnjaak

please. I will pay you. My twt wifeofboelacc

**Comment by Yessika224** [comment]
Message blackhathacker111 on telegram he’s the best for the job

**Comment by RedKatz** [comment]
txt me on twitter: https://twitter.com/redK15581932905?t=r-Xyq-3PC2P1jrElTZpqTQ&s=09
