### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by mega3000** [RedKatz/SocialMediaHackingToolkit#40]
Does the reporting still work? Which accounts is it using to report? It says its reporting but not really doing anything..
I really want to get it working!

**Comment by GitPro10** [comment]
it's fake probably

**Comment by anshy66566** [comment]
Please add the farcbook I'd Sukha Khadkhatri please add me email
***@***.***

**Comment by JvThe** [comment]
as i can see reporting is really done but not through the use of accounts, simply (as you can see in the source code) the following header is used, which will never be as efficcacious as accounts

**Comment by RedKatz** [comment]
> it's fake probably

no, here the report header used for reporting:

report_headers = {
"Accept": "*/*",
"Accept-Encoding": "gzip, deflate",
"Accept-Language": "tr-TR,tr;q=0.8,en-US;q=0.5,en;q=0.3",
"Cache-Control": "no-cache",
"Connection": "keep-alive",
"Content-Type": "application/x-www-form-urlencoded",
"DNT": "1",
"Host": "help.instagram.com",
"Origin": "help.instagram.com",
"Pragma": "no-cache",
"Referer": "https://help.instagram.com/contact/497253480400030",
"TE": "Trailers",
}


> as i can see reporting is really done but not through the use of accounts, simply (as you can see in the source code) the following header is used, which will never be as efficcacious as accounts

**Comment by mega3000** [comment]
But I'm wondering does the reporting actually work? As in, will it ban people?

**Comment by RedKatz** [comment]
> But I'm wondering does the reporting actually work? As in, will it ban people?

yes, it is not as efficient as a report made from an account but it does come, also if you are using windows it is possible thate the ip will be momentarily ban

**Comment by GitPro10** [comment]
> yes, it is not as efficient as a report made from an account but it does come

How many reports does it requires to ban people in this way?
Have you tested it?

**Comment by mega3000** [comment]
I'm currently testing on a pretty low following account. I've sent about 1500 so far haha. Let's see how long it takes :D

**Comment by mega3000** [comment]
So far I've ran 7500+ reports on 1 small account and it's not happened yet... wish it had ability to use accounts.
