### ISSUE TITLE
brute force not working

### ISSUE THREAD

**Issue by VIPHACKER100** [RedKatz/SocialMediaHackingToolkit#45]
please fix sleep time issues or not proper work bruteforce  . please update login agent   instagram

**Comment by amanpatel6778** [comment]
This tool working with sleep time issue and also showing wrong password but i give txt file with true password this tool not found my Instagram password

**Comment by Oyuntungalag1975** [comment]
Help me https://www.facebook.com/lhagwadorj.uuganbayar?mibextid=ZbWKwL passport

**Comment by RedKatz** [comment]
becouse the header changed, in the next versio i update this, the next version exit tomorrow
