### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Nixalakyr** [RedKatz/SocialMediaHackingToolkit#50]
After putting in this command: sudo dpkg -i windscribe-cli.deb
It shows this:
(Reading database ... 42896 files and directories currently installed.)
Preparing to unpack windscribe-cli.deb ...
Unpacking windscribe-cli (1.4-51) over (1.4-51) ...
dpkg: dependency problems prevent configuration of windscribe-cli:
 windscribe-cli depends on openvpn; however:
  Package openvpn is not installed.
 windscribe-cli depends on resolvconf; however:
  Package resolvconf is not installed.

dpkg: error processing package windscribe-cli (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 windscribe-cli

I don't really know how to fix it. Can somebody help me please? I'm using Kali Linux and I did create an account for windscribe.net before installing.

**Comment by RedKatz** [comment]
duplicated with wrong name, follow the issue here --> https://github.com/RedKatz/SocialMediaHackingToolkit/issues/53
