### ISSUE TITLE
Windscribe login error

### ISSUE THREAD

**Issue by zm-ibrahim** [RedKatz/SocialMediaHackingToolkit#51]
Windscribe keep showing when running command

```windscribe login```

it keep showing this error after submit user and password
"Error running login"

Is there any solution for this ? or should i just skip this step and go to the next step for installation ?

**Comment by zm-ibrahim** [comment]
Yes, I entered my username and password

**Comment by RedKatz** [comment]
you're on arch based? try to run this command systemctl start windscribe or windscribe-cli
