### ISSUE TITLE
Windscribe Error

### ISSUE THREAD

**Issue by Kahmikazi** [RedKatz/SocialMediaHackingToolkit#52]
dpkg: error processing archive windscribe-cli.deb (--install):
 package architecture (amd64) does not match system (i386)
Errors were encountered while processing:
 windscribe-cli.deb

When trying to install using Kali TUT

**Comment by RedKatz** [comment]
you're on 32 bit?

**Comment by Kahmikazi** [comment]
Yeah on a kali vm box

**Comment by RedKatz** [comment]
the package is only for 64 bit, if you're on 32bit check this tutorial https://www.geeksforgeeks.org/how-to-setup-vpn-on-ubuntu-linux-system-for-ip-spoofing-using-windscribe/
