### ISSUE TITLE
Errors were encountered while processing:  windscribe-cli

### ISSUE THREAD

**Issue by Supplyii** [RedKatz/SocialMediaHackingToolkit#53]
i am getting this error while running it in kali linux.

 (Reading database ... 21025 files and directories currently installed.)
Preparing to unpack windscribe-cli.deb ...
Unpacking windscribe-cli (1.4-51) over (1.4-51) ...
dpkg: dependency problems prevent configuration of windscribe-cli:
 windscribe-cli depends on openvpn; however:
  Package openvpn is not installed.
 windscribe-cli depends on resolvconf; however:
  Package resolvconf is not installed.

dpkg: error processing package windscribe-cli (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 windscribe-cli

**Comment by RedKatz** [comment]
you're on 32 bit or 64?

**Comment by Supplyii** [comment]
64

**Comment by Supplyii** [comment]
and using windows 10 pro

**Comment by RedKatz** [comment]
you run debian installation on windows 10

**Comment by RedKatz** [comment]
the vm is 32 or 64bit

**Comment by Supplyii** [comment]
64

**Comment by RedKatz** [comment]
install openvpn and resolvconf

**Comment by Supplyii** [comment]
Okk

**Comment by Supplyii** [comment]
Let me see

**Comment by Supplyii** [comment]
Did not worked

**Comment by Aaryano9** [comment]
Same error with me

**Comment by RedKatz** [comment]
if you are on a debian based distro try to install windscribe-cli manually, the package will be fixed in the next version
