### ISSUE TITLE
wordlist

### ISSUE THREAD

**Issue by patty2nicks** [RedKatz/SocialMediaHackingToolkit#60]
It has an error of wordlist not found despite the wordlist being created and in the folder

**Comment by sidduisnoobhacker** [comment]
bro how did you add it can you help me with adding

**Comment by Jahzkanga** [comment]
I tried this method it didn't work out either thanks to one of the hackers who helped me hack the account,he can brute force and hack all kind of accounts

**Comment by RedKatz** [comment]
solved, it was a problem within the batch file

**Comment by hashir1230** [comment]
bro i found problem in wordlist plz help me
