### ISSUE TITLE
Wordlist issue

### ISSUE THREAD

**Issue by IamBrixTM** [RedKatz/SocialMediaHackingToolkit#65]
Impressive how easy it was to get it running, and very easy to access. 

But I get stuck on wordlist with the following message: 
"EERROR 1x01: wordlist not found, please insert your wordlist into the 'wordlist' folder."

I've tried renaming, and different files but still can't get past it. Thanks.

**Comment by Yuvrajkadu2107ha** [comment]
How can I solve the problem of wordlist

**Comment by gk-sudo** [comment]
error bro how to solve?

**Comment by athanskie** [comment]
same here

**Comment by RedKatz** [comment]
solved, was a problem with the batch file
