### ISSUE TITLE
Low speed of BruteForce:

### ISSUE THREAD

**Issue by mrindianhacker** [RedKatz/SocialMediaHackingToolkit#67]
Everything is good in this script, but the main problem is the speed of password Bruteforce. it takes a lot of time to bruteforce the password. it it can be more speedy than it's too good. i request developer to please try to make it a bit of speedy so that it can take some less time to bruteforce password.

**Comment by IamBrixTM** [comment]
You had no trouble with wordlist? it just worked without doing anything other than adding passwords to the wordlist file? For some reason mine isn't going past that

**Comment by RedKatz** [comment]
the maximum speed is this to prevent the ip from being banned
