### ISSUE TITLE
'clear' ?

### ISSUE THREAD

**Issue by IskrenP** [RedKatz/SocialMediaHackingToolkit#71]
'clear' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Aqustor** [comment]
in cmd/utils.py
there is an error, line 515
change "os.system("clearr")" on "os.system("clear")"

**Comment by YaniOx** [comment]
> in cmd/utils.py there is an error, line 515 change "os.system("clearr")" on "os.system("clear")"

i did this, still doesnt change

**Comment by RedKatz** [comment]
on the latest versions of windows 11 cmd there is not this problem, try to update, in the readme file it says that only the latest version of windwos 11 is supported

**Comment by glassheronwarrior** [comment]
in the utils.py file there is no incorrect spelling of clearr....all have correct one
