### ISSUE TITLE
how do i install this?

### ISSUE THREAD

**Issue by matthewthepolymath** [RedKatz/SocialMediaHackingToolkit#75]
im new and dont understand anything, do I go to cmd or python? please help :)

**Comment by matthewthepolymath** [comment]
not answered yet

**Comment by shohag288** [comment]
> im new and dont understand anything, do I go to cmd or python? please help :)

I'm a cyber security consultant that is conducting and leading security audits, penetration testing engagements, and red team engagements to a variety of companies, ranging from enterprise-level companies to small start-ups.

Daily activities include, but are not limited to: penetration testing, red teaming, briefing, debriefing, other meetings.

Previously I did infrastructure management at an enterprise-level company where I was administrating three (3) active directory forests and did host-based incident response.

Certificates owned:
[+] CCNA Routing and Switching 1
[+] Cisco Cyber Operations Introduction
[+] Cisco Cyber Operations...
my WhatsApp number +8801314956025

**Comment by sahilgeorge** [comment]
Can you please tell me your operating system so that I can proceed with the installation steps according to your OS.

**Comment by joaoxy** [comment]
Já instalei ele mais como baixar alguma Word list ?
Uso o termux

**Comment by Rutwaza** [comment]
Kali linux

**Comment by Raju1977-fire** [comment]
Can u show me anything
I'm new here,and just instal termux 
Or u have video for this ?
So i can understand
Thank before 🙏

**Comment by RedKatz** [comment]
follow the instructions in the readme file
