### ISSUE TITLE
my terminal crashed when i choose the VPN off or on 

### ISSUE THREAD

**Issue by mahjoubhlel** [RedKatz/SocialMediaHackingToolkit#80]
my terminal crashed when i choose the VPN off or on

**Comment by sahilgeorge** [comment]
What OS are you running this on? If on Linux, which terminal application are you using?

**Comment by mahjoubhlel** [comment]
On windows 10

**Comment by sahilgeorge** [comment]
Ok. Let me check.

**Comment by mahjoubhlel** [comment]
Any updates?

**Comment by RedKatz** [comment]
on windows 10 vpn is off, so you need to put vpn off

**Comment by mahjoubhlel** [comment]
i do bro !! when i start the terminal close ! auto

**Comment by mahjoubhlel** [comment]
[image: image.png]

like this that mean my insagram mass reporter works or not ?
