### ISSUE TITLE
module not installed or found ' rich '

### ISSUE THREAD

**Issue by KAMARALAMKHAN786** [RedKatz/SocialMediaHackingToolkit#86]
module not installed or found ' rich ' even after installing 'rich'  module!

**Comment by RedKatz** [comment]
you're on windows?

**Comment by PremPatil2608** [comment]
> 

no

**Comment by Kokothecreator** [comment]
I am also having same issue, I'm on termux

**Comment by RedKatz** [comment]
run pip3 install rich, if it doesn't work it's a problem with your device try updating the packages
