### ISSUE TITLE
Instagram Bruteforce Bug

### ISSUE THREAD

**Issue by lokeshpanwar1** [RedKatz/SocialMediaHackingToolkit#88]
I'm using kali linux and done all processes as written in readme file

When I'm not using vpn then it just show password as written in my password file 
My password file contains 8 password among them one is correct but it is not showing any sign that it is correct password or not 

When I'm using windscribe vpn it enable firewall and disable again for every password

Like everything is going fine taking input from file and all just one thing is missing that it doesn't show which one is correct password as I double checked via login in browser that my password is correct

**Comment by Kokothecreator** [comment]
Unrelated, but how did you get password file?

**Comment by RedKatz** [comment]
>When I'm not using vpn then it just show password as written in my password file
My password file contains 8 password among them one is correct but it is not showing any sign that it is correct password or not

Is because when you don't use vpn your ip is banned
