### ISSUE TITLE
twitter bruteforce

### ISSUE THREAD

**Issue by aguja262** [RedKatz/SocialMediaHackingToolkit#94]
I'm trying the bruteforce option on twitter but I don't know how effective it really is. Someone tried it and it worked for him? or this option is still under development? because mostly in the repository bruteforce is talked about in instagram and not in the other options.
I also think that the wordlists available are not the most suitable for twitter, at least the most known ones. Does anyone have any good wordlists? also, is it correct to say bruteforce option when it's a dictionary attack or are they synonymous terms?

**Comment by reiayanamy** [comment]
to me sometimes it works and sometimes it doesn't, instagram always goes but twitter sometimes it doesn't, I think it's due to my ip being banned in fact it doesn't even let me access the page for a few hours

i use windows

**Comment by aguja262** [comment]
> to me sometimes it works and sometimes it doesn't, instagram always goes but twitter sometimes it doesn't, I think it's due to my ip being banned in fact it doesn't even let me access the page for a few hours
> 
> i use windows

I see, also at the beginning when it gives you to choose options it asks you if you want vpn to be used or not, didn't you try that or it just doesn't work?
