### ISSUE TITLE
Mass Report -Instagram

### ISSUE THREAD

**Issue by teddblaker3** [RedKatz/SocialMediaHackingToolkit#95]
I have analyzed all the code you provided on GitHub some similarities are on on the repos,

How this works lets investigate.
If the username provided in the script is incorrect, the login attempts will fail, and the script will continue trying passwords without success. What about passing Instagram captcha? If the captcha appears from Instagram side then no errors shown in terminal the simulation of attack is continuous.

Instagram mass reporting  from green - example: [ 53 ] gets red, does it mean report did not passed, it can be.

In terminal 320k passwords passed several times without any errors. Interesting I have checked your code looks like without errors written and yes I did not input right password in a psw file but the main problem is tat Instagram account did not ended up "under review" or to similar problem after so many attempts to log in.

1 attempt - public WiFi used
2 attempt - VPN
3 attempt Tor socks

result is above

Can you make some changes so if the error appears or IP band or other scenarios like Instagram captcha, then script informs the user in terminal not wasting resources.

**Comment by riot17** [comment]
@6769_shivangi

**Comment by teddblaker3** [comment]
I've customized a script to display me when an IP is banned. The challenge is that this VPN IP's are banned - because of all Free users on same Free VPN. To work around this, I integrated Tor. Although many Tor IPs are also blocked, some still work but it takes time for Tor to change addresses - too slow.
