### ISSUE TITLE
Windscribe: command not found

### ISSUE THREAD

**Issue by PushkarOP** [RedKatz/SocialMediaHackingToolkit#96]
[
![Screenshot_20230716-073616](https://github.com/RedKatz/SocialMediaHackingToolkit/assets/84075300/1f79856c-0a33-4b30-96cd-b0a6e59d8363)
](url)

**Comment by PushkarOP** [comment]
One more error when i put 133mb file:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 923: invalid continuation byte

**Comment by RedKatz** [comment]
first error: you did not install windscribe correctly, and even if you had, you could not use it via ssh


second error: the wordlist contains special characters that cannot be decoded, try u
